[WIP] docs(type): Provides an initial documentation document for the Type component
php-standard-library/php-standard-library pull request #462
Opened 2024-04-05 13:44 UTC by veewee

The README is based on the structure in `php-standard-library/php-standard-library.github.io` so that it can be displayed on the website. We concluded to add documentation in this repo, so I am providing it here already.

Currently it's an initial draft aiming on explaining what the component can be used for.
It now covers:

- Introduction
- Converted type
- Shape type

I am focussing on providing very detailed types and ideas on how to use them so that we maybe don't need to explain every single type in this package. (like int, float, ...)

2024-04-05 13:45 UTC, azjezz commented
great start! could you remove this from `docs/documentor.php` and add it in the readme template like the other ones: https://github.com/azjezz/psl/blob/next/docs/templates/README.template.md#components ? thanks!

2024-04-05 13:47 UTC, azjezz commented
> The README is based on the structure in php-standard-library/php-standard-library.github.io so that it can be displayed on the website.

Not sure if we want to keep the same format, as people would most likely read this on GitHub and locally, so maybe we can come up with a better format/style for documentation?

2024-04-05 13:49 UTC, veewee commented
> Not sure if we want to keep the same format, as people would most likely read this on GitHub and locally, so maybe we can come up with a better format/style for documentation?

I can base it on the format in https://github.com/azjezz/psl/blob/next/src/Psl/Async/README.md ?

2024-04-05 14:37 UTC, azjezz commented
maybe? i don't know really. up to you :D

2024-04-09 14:09 UTC, veewee commented
> maybe? i don't know really. up to you :D

What do you think about current structure?
It's how I do it on my projects and it has some advantages:

* No usage of lists, making it easier to maintain
* Function names (and classes, ...) are level 4 headers that make it possible to link directly to that section of the page.
* These titles can be used as anchors to the code so that you can easily look at it yourself
* Separation is done with a `---` gives you a clear indication where docs for that function stop.

I'm also trying to give it a consistent structure:

* title
* hack-style type information
* What does assert / coerce act like
* Optional example (if its worth adding)

2024-04-16 17:31 UTC, azjezz requested changes
This looks good overall.

I am still not sure about the format, but, we can keep it as is for now, and if we later decide on a different format, we can change it ( along with the other documentation files ).

2024-04-16 17:31 UTC, azjezz commented on src/Psl/Type/README.md
> +]);
This example will give an error, it should be either `coerce` or provide an instance of `MapInterface`.

2024-04-16 17:31 UTC, azjezz commented on src/Psl/Type/README.md
> +]);
same as before, this should be an instance of `MutableMapInterface`.

2024-04-16 17:31 UTC, azjezz commented on src/Psl/Type/README.md
> +]);
needs to be an instance of `VectorInterface`.

2024-04-16 17:31 UTC, azjezz commented on src/Psl/Type/README.md
> +]);
same here.

2024-04-17 05:08 UTC, veewee commented
> I am still not sure about the format,...

Let me know if there is something specific you don't like, I can always change the format..

2024-04-17 21:03 UTC, azjezz approved these changes

2024-04-17 21:03 UTC, merged